// Code generated by go run ./cmd/reset; DO NOT EDIT.
// This file was generated by reset main.go

package models

func (v *InsertData) Reset() {
	if v == nil {
		return
	}

	v.Key = ""

	v.Value = ""

	v.UserId = ""

}

func (v *ShortenReq) Reset() {
	if v == nil {
		return
	}

	v.Url = ""

}
